name: 'Lint & Test'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  pull-requests: read
  statuses: write

jobs:
  main:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Linters
        run: pnpm run lint
      - name: Setup Playwright
        run: pnpm exec playwright install chromium
      - name: Run Unit Tests
        run: pnpm test
      - name: Run Storybook Tests
        run: pnpm run build-storybook
      - name: Run Chromatic
        run: pnpm run chromatic
